+define+FORMAL
+define+FORMAL_FAIR
+define+FORMAL_TYPE_FAIR
+define+DUMB_COMPILER
+incdir+../env
+incdir+../properties
../rtl/common/core_pkg.sv
../rtl/coherency/coherency_pkg.sv
../rtl/cache/cache_pkg.sv
../rtl/common/interface_pkg.sv
../rtl/coherency/directory_pkg.sv
../rtl/coherency/directory.sv
../env/directory_type_fair.sv
