#include "Witness.h"
#include <algorithm>
#include <cctype>
#include <fstream>
#include <iomanip>
#include <map>
#include <sstream>
#include <stdexcept>
#include <unordered_map>

namespace emul::formal {
namespace {
struct SignalInfo { std::string name; bool input = false; };

std::unordered_map<uint64_t, SignalInfo> read_signals(
    const std::filesystem::path& model) {
    std::unordered_map<uint64_t, SignalInfo> result;
    std::ifstream input(model);
    std::string line;
    while (std::getline(input, line)) {
        std::istringstream fields(line);
        uint64_t id = 0;
        std::string opcode;
        std::string sort;
        std::string name;
        if (!(fields >> id >> opcode >> sort >> name)) continue;
        if (opcode == "input" || opcode == "state")
            result[id] = {name, opcode == "input"};
    }
    return result;
}

std::string vcd_id(uint64_t id) { return "v" + std::to_string(id); }

std::string vcd_name(std::string name) {
    for (auto& character : name)
        if (!std::isalnum(static_cast<unsigned char>(character)) &&
            character != '_' && character != '$') character = '_';
    if (name.empty()) return "signal";
    return name;
}
}

Witness decode_btor_witness(const std::filesystem::path& model,
                            const std::string& text) {
    const auto names = read_signals(model);
    Witness witness;
    WitnessStep* current = nullptr;
    bool input_section = false;
    std::istringstream input(text);
    std::string line;
    while (std::getline(input, line)) {
        if (line.size() > 1 && (line[0] == '#' || line[0] == '@')) {
            input_section = line[0] == '@';
            uint32_t step = 0;
            try { step = static_cast<uint32_t>(std::stoul(line.substr(1))); }
            catch (...) { continue; }
            auto found = std::find_if(witness.steps.begin(), witness.steps.end(),
                [step](const auto& value) { return value.index == step; });
            if (found == witness.steps.end()) {
                witness.steps.push_back({step, {}});
                current = &witness.steps.back();
            } else current = &*found;
            continue;
        }
        if (!current) continue;
        std::istringstream fields(line);
        uint64_t id = 0;
        std::string bits;
        if (!(fields >> id >> bits)) continue;
        std::string witness_name;
        fields >> witness_name;
        if (!witness_name.empty()) {
            if (const auto suffix = witness_name.find_last_of("#@");
                suffix != std::string::npos)
                witness_name.erase(suffix);
            // State and input indices are independent namespaces in the BTOR
            // witness format. Keep them disjoint for VCD identifiers.
            const auto signal_id = id | (input_section ? (uint64_t{1} << 63) : 0);
            current->signals.push_back(
                {signal_id, witness_name, bits, input_section});
            continue;
        }
        auto found = names.find(id);
        if (found == names.end()) continue;
        current->signals.push_back(
            {id, found->second.name, bits, found->second.input});
    }
    std::sort(witness.steps.begin(), witness.steps.end(),
              [](const auto& a, const auto& b) { return a.index < b.index; });
    return witness;
}

void write_witness_text(const Witness& witness,
                        const std::filesystem::path& path) {
    std::ofstream output(path);
    if (!output) throw std::runtime_error("cannot write witness: " + path.string());
    for (const auto& step : witness.steps) {
        output << "Cycle " << step.index << "\n";
        for (const auto& signal : step.signals)
            output << "  " << signal.name << " = " << signal.bits << '\n';
        output << '\n';
    }
}

void write_witness_vcd(const Witness& witness,
                       const std::filesystem::path& path,
                       std::string_view timescale) {
    std::map<uint64_t, WitnessSignal> signals;
    for (const auto& step : witness.steps)
        for (const auto& signal : step.signals)
            signals.emplace(signal.id, signal);
    std::ofstream output(path);
    if (!output) throw std::runtime_error("cannot write VCD: " + path.string());
    output << "$date generated by hwc $end\n$version hwc formal $end\n"
           << "$timescale " << timescale << " $end\n$scope module formal $end\n";
    for (const auto& [id, signal] : signals)
        output << "$var wire " << std::max<size_t>(1, signal.bits.size()) << ' '
               << vcd_id(id) << ' ' << vcd_name(signal.name) << " $end\n";
    output << "$upscope $end\n$enddefinitions $end\n";
    for (const auto& step : witness.steps) {
        output << '#' << step.index << '\n';
        for (const auto& signal : step.signals) {
            if (signal.bits.size() == 1)
                output << signal.bits << vcd_id(signal.id) << '\n';
            else
                output << 'b' << signal.bits << ' ' << vcd_id(signal.id) << '\n';
        }
    }
}
}
